use anyhow::{bail, Context, Result};
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

/// Role label lists used by the classifier to determine backend vs frontend.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RoleLabels {
    #[serde(default = "default_backend_labels")]
    pub backend: Vec<String>,
    #[serde(default = "default_frontend_labels")]
    pub frontend: Vec<String>,
}

impl Default for RoleLabels {
    fn default() -> Self {
        Self {
            backend: default_backend_labels(),
            frontend: default_frontend_labels(),
        }
    }
}

fn default_backend_labels() -> Vec<String> {
    ["backend", "api", "kernel", "rust", "database", "performance"]
        .iter()
        .map(|s| s.to_string())
        .collect()
}

fn default_frontend_labels() -> Vec<String> {
    ["frontend", "ui", "dashboard", "ux", "html", "css"]
        .iter()
        .map(|s| s.to_string())
        .collect()
}

/// Pipeline configuration -- loaded from `.pipeline/config.toml` in the repo root.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PipelineConfig {
    #[serde(default = "default_base_branch")]
    pub base_branch: String,

    #[serde(default)]
    pub backlog_base: String,

    #[serde(default)]
    pub backlog_project: String,

    #[serde(default = "default_max_budget_usd")]
    pub max_budget_usd: f64,

    #[serde(default = "default_max_stories_per_session")]
    pub max_stories_per_session: u32,

    #[serde(default = "default_max_iterations")]
    pub max_iterations: u32,

    #[serde(default = "default_max_cycles_per_story")]
    pub max_cycles_per_story: u32,

    /// Repo map: 0 = disabled (default). Set to 100 for large unfamiliar repos.
    #[serde(default)]
    pub repo_map_lines: u32,

    #[serde(default = "default_openfang_url")]
    pub openfang_url: String,

    #[serde(default = "default_poll_interval_secs")]
    pub poll_interval_secs: u64,

    /// Role label classification rules.
    #[serde(default)]
    pub roles: RoleLabels,
}

fn default_base_branch() -> String { "dev".to_string() }
fn default_max_budget_usd() -> f64 { 3.00 }
fn default_max_stories_per_session() -> u32 { 5 }
fn default_max_iterations() -> u32 { 10 }
fn default_max_cycles_per_story() -> u32 { 3 }
fn default_openfang_url() -> String { "http://127.0.0.1:50051".to_string() }
fn default_poll_interval_secs() -> u64 { 300 }

impl Default for PipelineConfig {
    fn default() -> Self {
        Self {
            base_branch: default_base_branch(),
            backlog_base: String::new(),
            backlog_project: String::new(),
            max_budget_usd: default_max_budget_usd(),
            max_stories_per_session: default_max_stories_per_session(),
            max_iterations: default_max_iterations(),
            max_cycles_per_story: default_max_cycles_per_story(),
            repo_map_lines: 0,
            openfang_url: default_openfang_url(),
            poll_interval_secs: default_poll_interval_secs(),
            roles: RoleLabels::default(),
        }
    }
}

impl PipelineConfig {
    /// Load config from `.pipeline/config.toml` in `repo_root`.
    pub fn load(repo_root: &Path) -> Result<Self> {
        let path = repo_root.join(".pipeline").join("config.toml");
        if !path.exists() {
            bail!(
                "No .pipeline/config.toml found at {}.\nRun `pipeline setup` first.",
                path.display()
            );
        }
        let raw = std::fs::read_to_string(&path)
            .with_context(|| format!("Failed to read {}", path.display()))?;
        let cfg: Self = toml::from_str(&raw)
            .with_context(|| format!("Failed to parse {}", path.display()))?;
        Ok(cfg)
    }

    pub fn backend_file(&self, repo_root: &Path) -> PathBuf {
        repo_root.join(".pipeline").join("backend.md")
    }

    pub fn frontend_file(&self, repo_root: &Path) -> PathBuf {
        repo_root.join(".pipeline").join("frontend.md")
    }

    pub fn guards_file(&self, repo_root: &Path) -> PathBuf {
        repo_root.join(".pipeline").join("guards.toml")
    }
}

// ---------------------------------------------------------------------------
// File templates
// All templates use concat! or plain string literals to avoid raw-string
// delimiter collisions with sequences like "#  that appear in TOML content.
// ---------------------------------------------------------------------------

pub fn config_toml_template() -> String {
    concat!(
        "# Pipeline configuration -- generated by `pipeline setup`\n",
        "# Edit values marked TODO before running the pipeline.\n",
        "\n",
        "base_branch = \"dev\"          # Change to \"main\" if this repo works off main\n",
        "backlog_base = \"TODO\"        # e.g. https://yourorg.backlog.com\n",
        "backlog_project = \"TODO\"     # e.g. MYPROJECT\n",
        "max_budget_usd = 3.00        # Per-story Claude CLI cost cap in USD\n",
        "max_stories_per_session = 5  # Force session refresh (Ralph loop) after N stories\n",
        "max_iterations = 10          # Max retry loops per story before blocking on human\n",
        "max_cycles_per_story = 3     # Max Flag/Reject cycles before escalation\n",
        "repo_map_lines = 0           # 0 = disabled. Set to 100 for large unfamiliar repos.\n",
        "openfang_url = \"http://127.0.0.1:50051\"  # OpenFang API for gates + dashboard\n",
        "poll_interval_secs = 300     # Backlog polling interval (seconds). Default: 5 min.\n",
        "\n",
        "[roles]\n",
        "# Keyword → role mapping. Matched against issueType.name, category names, then summary.\n",
        "backend  = [\"backend\", \"api\", \"kernel\", \"rust\", \"database\", \"performance\"]\n",
        "frontend = [\"frontend\", \"ui\", \"dashboard\", \"ux\", \"html\", \"css\"]\n",
    ).to_string()
}

pub fn guards_toml_template() -> String {
    // Written as a plain string to avoid raw-string delimiter collisions.
    // The TOML single-quoted strings (pattern = '...') and exclude_patterns
    // containing "#..." would prematurely close r#"..."# raw strings.
    let mut s = String::new();

    s.push_str("# Guard rules -- run after every story commit, before human gate.\n");
    s.push_str("# severity: \"error\" (blocks gate) | \"warn\" (shown but does not block)\n");
    s.push_str("# enabled: true | false\n\n");

    append_rule(&mut s, "no_hardcoded_ports", "error",
        "Hardcoded port numbers in string literals",
        r#"port.*=.*"\d{4,5}"|\d{4,5}".*port|bind.*"\d{4,5}""#,
        &[]);

    append_rule(&mut s, "no_hardcoded_ips", "warn",
        "Hardcoded IP addresses (excluding 0.0.0.0, 127.0.0.1, test/mock)",
        r#""[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}""#,
        &["0\\.0\\.0\\.0", "127\\.0\\.0\\.1", "169\\.254", "test", "mock", "block"]);

    append_rule(&mut s, "no_unwrap_production", "warn",
        "Unwrap calls outside test code (warn -- FPs from in-file test modules)",
        r"\.unwrap\(\)",
        &["mod tests", "assert", "let _ =", "_test.rs"]);

    append_rule(&mut s, "no_todo_left_in_impl", "error",
        "TODO/FIXME/HACK markers left in implementation",
        "TODO|FIXME|HACK",
        &["_test.rs", ".md"]);

    append_rule(&mut s, "no_magic_numbers", "warn",
        "Magic number literals not assigned to a named constant",
        r"const [A-Z_]+ = [0-9]+",
        &[]);

    append_rule(&mut s, "no_credentials_in_code", "error",
        "Hardcoded credentials or secrets (excluding test fixtures)",
        r#"password|api_key|secret.*=.*""#,
        &["test-", "fake-", "mock-", "my-", "sample-", "example-"]);

    append_rule(&mut s, "no_hardcoded_secrets", "error",
        "Bearer tokens or API key strings (20+ char alphanumeric)",
        r#""[A-Za-z0-9_\-]{20,}""#,
        &["test", "example", "placeholder", "YOUR_", "TODO"]);

    append_rule(&mut s, "no_debug_print", "warn",
        "Debug print statements left in production code",
        r"println!|dbg!|eprintln!",
        &["_test.rs", "mod tests"]);

    append_rule(&mut s, "business_logic_in_routes", "warn",
        "Handler functions with excessive lines (indicates logic leak into routes)",
        "LINE_COUNT_CHECK",
        &[]);
    // Mark last rule as awk-based
    s.push_str("awk_check = true\nmax_lines = 30\n");

    s
}

fn append_rule(out: &mut String, name: &str, severity: &str, description: &str, pattern: &str, excludes: &[&str]) {
    out.push_str("[[rule]]\n");
    out.push_str(&format!("name = \"{}\"\n", name));
    out.push_str(&format!("severity = \"{}\"\n", severity));
    out.push_str("enabled = true\n");
    out.push_str(&format!("description = \"{}\"\n", description));
    out.push_str(&format!("pattern = '{}'\n", pattern));
    if !excludes.is_empty() {
        let quoted: Vec<String> = excludes.iter().map(|e| format!("\"{}\"", e)).collect();
        out.push_str(&format!("exclude_patterns = [{}]\n", quoted.join(", ")));
    }
    out.push('\n');
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn test_default_config_values() {
        let cfg = PipelineConfig::default();
        assert_eq!(cfg.base_branch, "dev");
        assert_eq!(cfg.max_budget_usd, 3.00);
        assert_eq!(cfg.max_stories_per_session, 5);
        assert_eq!(cfg.max_iterations, 10);
        assert_eq!(cfg.max_cycles_per_story, 3);
        assert_eq!(cfg.repo_map_lines, 0);
        assert_eq!(cfg.openfang_url, "http://127.0.0.1:50051");
        assert_eq!(cfg.poll_interval_secs, 300);
        assert!(cfg.backlog_base.is_empty());
        assert!(cfg.backlog_project.is_empty());
    }

    #[test]
    fn test_config_toml_template_is_valid_toml() {
        let tmpl = config_toml_template();
        // Must parse without error
        let parsed: Result<toml::Value, _> = toml::from_str(&tmpl);
        assert!(parsed.is_ok(), "config template is not valid TOML: {:?}", parsed.err());
    }

    #[test]
    fn test_config_toml_template_contains_required_keys() {
        let tmpl = config_toml_template();
        assert!(tmpl.contains("base_branch"));
        assert!(tmpl.contains("backlog_base"));
        assert!(tmpl.contains("backlog_project"));
        assert!(tmpl.contains("max_budget_usd"));
        assert!(tmpl.contains("openfang_url"));
        assert!(tmpl.contains("poll_interval_secs"));
    }

    #[test]
    fn test_guards_toml_template_contains_all_rules() {
        let tmpl = guards_toml_template();
        assert!(tmpl.contains("no_hardcoded_ports"));
        assert!(tmpl.contains("no_hardcoded_ips"));
        assert!(tmpl.contains("no_unwrap_production"));
        assert!(tmpl.contains("no_todo_left_in_impl"));
        assert!(tmpl.contains("no_credentials_in_code"));
        assert!(tmpl.contains("no_hardcoded_secrets"));
        assert!(tmpl.contains("no_debug_print"));
        assert!(tmpl.contains("business_logic_in_routes"));
        assert!(tmpl.contains("[[rule]]"));
    }

    #[test]
    fn test_guards_toml_template_has_valid_rule_structure() {
        let tmpl = guards_toml_template();
        // Every rule must have name, severity, enabled
        for rule_block in tmpl.split("[[rule]]").skip(1) {
            assert!(rule_block.contains("name ="), "rule block missing name");
            assert!(rule_block.contains("severity ="), "rule block missing severity");
            assert!(rule_block.contains("enabled ="), "rule block missing enabled");
        }
    }

    #[test]
    fn test_load_config_from_toml() {
        let dir = TempDir::new().unwrap();
        let pipeline_dir = dir.path().join(".pipeline");
        std::fs::create_dir_all(&pipeline_dir).unwrap();
        std::fs::write(
            pipeline_dir.join("config.toml"),
            "base_branch = \"main\"\nbacklog_base = \"https://test.backlog.com\"\nbacklog_project = \"TEST\"\n",
        )
        .unwrap();
        let cfg = PipelineConfig::load(dir.path()).unwrap();
        assert_eq!(cfg.base_branch, "main");
        assert_eq!(cfg.backlog_base, "https://test.backlog.com");
        assert_eq!(cfg.backlog_project, "TEST");
        // Unset fields should use defaults
        assert_eq!(cfg.max_budget_usd, 3.00);
    }

    #[test]
    fn test_load_config_fails_without_file() {
        let dir = TempDir::new().unwrap();
        assert!(PipelineConfig::load(dir.path()).is_err());
    }

    #[test]
    fn test_config_file_paths() {
        let dir = TempDir::new().unwrap();
        let cfg = PipelineConfig::default();
        assert_eq!(cfg.backend_file(dir.path()), dir.path().join(".pipeline").join("backend.md"));
        assert_eq!(cfg.frontend_file(dir.path()), dir.path().join(".pipeline").join("frontend.md"));
        assert_eq!(cfg.guards_file(dir.path()), dir.path().join(".pipeline").join("guards.toml"));
    }
}
